services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb

    secrets:
      - root_passwd
      - user_passwd


secrets:
  root_passwd:
    file: ../secrets/root_passwd.txt
  user_passwd:
    file: ../secrets/user_passwd.txt