services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:v1
    container_name: mariadb
    secrets:
      - root_passwd
      - user_passwd
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx:v1
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
    - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:v1
    container_name: wordpress
    secrets:
      - user_passwd
      - wp_admin_passwd
      - wp_user_passwd
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb

secrets:
  root_passwd:
    file: ../secrets/root_passwd.txt
  user_passwd:
    file: ../secrets/user_passwd.txt
  wp_admin_passwd:
    file: ../secrets/wp_admin_passwd.txt
  wp_user_passwd:
    file: ../secrets/wp_user_passwd.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge