services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb

    secrets:
      - root_passwd
      - user_passwd

  
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

secrets:
  root_passwd:
    file: ../secrets/root_passwd.txt
  user_passwd:
    file: ../secrets/user_passwd.txt